### ISSUE TITLE
problem with module bind

### ISSUE THREAD

**Issue by xiuliren** [chinakook/PointCNN.MX#1]
Hi, thanks for making this package.
I just tried, but have some problems. I am not familiar with mxnet, but would like to try. Maybe there is a simple fix.

I have compiled the master branch of mxnet using cuda 9.2 and cudnn 7.
```
Traceback (most recent call last):                                                                    
  File "pointcnn_cls.py", line 136, in <module>                                                       
    mod.bind(data_shapes=[('data',(batch_size_train, sample_num_train,3))], label_shapes=[('softmax_la
bel',(batch_size_train, probs_shape[1]))], for_training=True, shared_module=mod)                      
  File "/opt/incubator-mxnet/python/mxnet/module/module.py", line 416, in bind                        
    shared_module.binded and shared_module.params_initialized                                         
AssertionError                                                                                        
```

If I change the `shared_module=mod` to `shared_module=None`, the program runs but it seems that it is not learning anything. I have ran for about a hour, and the value keep about 0.1 which is random guess.

**Comment by chinakook** [comment]
It's may caused by the recent PR: https://github.com/apache/incubator-mxnet/pull/12155
I'll try to fix it.

**Comment by chinakook** [comment]
It's caused by the recent PR: https://github.com/apache/incubator-mxnet/pull/12155
I'll fix it later.

**Comment by chinakook** [comment]
It's fixed in my master branch. @jingpengw

**Comment by xiuliren** [comment]
thanks a lot! It works great!
